// <auto-generated />
using System;
using HostAPI.Storing;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HostAPI.Migrations
{
    [DbContext(typeof(HostContext))]
    [Migration("20210322160038_poop")]
    partial class poop
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HostAPI.Domain.Models.Game", b =>
                {
                    b.Property<long>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GameName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntityId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("HostAPI.Domain.Models.Host", b =>
                {
                    b.Property<string>("RoomCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("gameEntityId")
                        .HasColumnType("bigint");

                    b.HasKey("RoomCode");

                    b.HasIndex("gameEntityId");

                    b.ToTable("Hosts");
                });

            modelBuilder.Entity("HostAPI.Domain.Models.Player", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HostRoomcode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("score")
                        .HasColumnType("int");

                    b.HasKey("name");

                    b.HasIndex("HostRoomcode");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("HostAPI.Domain.Models.Host", b =>
                {
                    b.HasOne("HostAPI.Domain.Models.Game", "game")
                        .WithMany()
                        .HasForeignKey("gameEntityId");

                    b.Navigation("game");
                });

            modelBuilder.Entity("HostAPI.Domain.Models.Player", b =>
                {
                    b.HasOne("HostAPI.Domain.Models.Host", null)
                        .WithMany("Players")
                        .HasForeignKey("HostRoomcode");
                });

            modelBuilder.Entity("HostAPI.Domain.Models.Host", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
